name: voice-feature-store
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip
  - openjdk=11.0.21  # For Flink
  - cudatoolkit=11.8.0  # Optional: for GPU acceleration
  - ffmpeg=4.4.2  # For audio processing
  - pip:
    - -e .  # Install our package in editable mode
    - -e .[dev]  # Install dev dependencies